### ISSUE TITLE
Forward function in simple.py

### ISSUE THREAD

**Issue by udion** [uber-research/differentiable-plasticity#5]
In the paper https://arxiv.org/pdf/1804.02464.pdf, equation 1 does not have input added but the code in `simple.py` has an additional term of `input`
https://github.com/uber-research/differentiable-plasticity/blob/9214eea7ec926071191e6d54e2867be336afe051/simple/simple.py#L118

Can you please explain this, maybe I'm misinterpreting something.

Thanks!

**Comment by ThomasMiconi** [comment]
Equations 1 and 2 in the paper describe only the plastic connections! The network must receive inputs to perform its task. In these experiments, the input connections are not plastic: only the recurrent connections are. The input is simply added to recurrent excitation, which is how standard recurrent networks operate.

**Comment by udion** [comment]
@ThomasMiconi 

Thanks! yes, it makes sense.

Quick question, do you think the if we have only pure forward connections then plasticity would help in certain tasks?

**Comment by ThomasMiconi** [comment]
Yes. The Omniglot task uses a feedforward network. Plasticity may help for any task that extends over multiple time steps.
